// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edsjhqlqzvvkwdhqwzxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkc2pocWxxenZ2a3dkaHF3enhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODIzNDUsImV4cCI6MjA3NDU1ODM0NX0.FkWzlrwYfAa9rZaJ4Nblc_DNlcV4FPC0qk2RZyKjqnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});